const mockCourses = [
  {
    id: "1",
    name: "Khóa học cờ vua cơ bản cho trẻ em",
    imageUrl: "https://via.placeholder.com/300x150.png?text=Course+1",
    rating: 5,
    reviewsCount: 12,
    studentsCount: 8,
    duration: "5h 20m",
    instructor: "Daisy Cờ Vua",
    categories: ["Chiến thuật", "Cơ bản"],
    price: 250000,
    originalPrice: 300000,
    totalStock: 10,
  },
  {
    id: "2",
    name: "Ponziani – Vũ Khí Bất Ngờ Trong Khai Cuộc",
    imageUrl: "https://via.placeholder.com/300x150.png?text=Course+2",
    rating: 4,
    reviewsCount: 5,
    studentsCount: 5,
    duration: "2h 30m",
    instructor: "Daisy Cờ Vua",
    categories: ["Opening Repertoire"],
    price: 59000,
    originalPrice: 300000,
    totalStock: 20,
  },
  {
    id: "3",
    name: "Bậc Thầy Phòng Thủ Trong Cờ Vua",
    imageUrl: "https://via.placeholder.com/300x150.png?text=Course+3",
    rating: 4,
    reviewsCount: 8,
    studentsCount: 1,
    duration: "10h 30m",
    instructor: "Daisy Cờ Vua",
    categories: ["Phòng thủ", "Tính toán"],
    price: 249000,
    originalPrice: 400000,
    totalStock: 15,
  },
  {
    id: "4",
    name: "Bậc Thầy Phòng Thủ Trong Cờ Vua",
    imageUrl: "https://via.placeholder.com/300x150.png?text=Course+3",
    rating: 4,
    reviewsCount: 8,
    studentsCount: 1,
    duration: "10h 30m",
    instructor: "Daisy Cờ Vua",
    categories: ["Phòng thủ", "Tính toán"],
    price: 249000,
    originalPrice: 400000,
    totalStock: 15,
  },
  {
    id: "5",
    name: "Bậc Thầy Phòng Thủ Trong Cờ Vua",
    imageUrl: "https://via.placeholder.com/300x150.png?text=Course+3",
    rating: 4,
    reviewsCount: 8,
    studentsCount: 1,
    duration: "10h 30m",
    instructor: "Daisy Cờ Vua",
    categories: ["Phòng thủ", "Tính toán"],
    price: 249000,
    originalPrice: 400000,
    totalStock: 15,
  },
  {
    id: "6",
    name: "Bậc Thầy Phòng Thủ Trong Cờ Vua",
    imageUrl: "https://via.placeholder.com/300x150.png?text=Course+3",
    rating: 4,
    reviewsCount: 8,
    studentsCount: 1,
    duration: "10h 30m",
    instructor: "Daisy Cờ Vua",
    categories: ["Phòng thủ", "Tính toán"],
    price: 249000,
    originalPrice: 400000,
    totalStock: 15,
  },
];

export default mockCourses;
